env:
  - GO111MODULE=on
before:
  hooks:
  - go mod tidy
gomod:
  proxy: false

builds:
- env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "7"
  ignore:
  - goos: windows
    goarch: arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{ .Version }} -X main.commitSHA={{.Commit}} -X main.buildDate={{ .Date }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch', 'go mod tidy']

archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip
  files:
  - README.md
  - LICENSE
  rlcp: true

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  maintainer: 'Abdul Khaliq <a.khaliq@outlook.my>'
  description: Dockerhub rate limit exporter.
  license: MIT
  formats:
  - deb
  - rpm
  - apk

brews:
- tap:
    owner: kha7iq
    name: homebrew-tap
  folder: Formula
  goarm: "7"
  homepage: https://ncp.lmno.pk
  description: NCP is a file transfer utility that enables efficient copying of files to and from an NFS server.
  license: MIT
  test: |
    system "#{bin}/ncp -v"
  install: |-
    bin.install "ncp"

scoops:
- bucket:
    owner: kha7iq
    name: scoop-bucket
  homepage:  https://ncp.lmno.pk
  description: NCP is a file transfer utility that enables efficient copying of files to and from an NFS server.
  license: MIT

aurs:
- homepage:  https://ncp.lmno.pk
  description: NCP is a file transfer utility that enables efficient copying of files to and from an NFS server.
  maintainers:
    - 'Abdul Khaliq <a.khaliq@outlook.my>'
  license: MIT
  private_key: '{{ .Env.AUR_KEY }}'
  git_url: 'ssh://aur@aur.archlinux.org/ncp-bin.git'
  package: |-
    # bin
    install -Dm755 "./ncp" "${pkgdir}/usr/bin/ncp"

    # license
    install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/ncp/LICENSE"

dockers:
- image_templates:
  - 'khaliq/ncp:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
- image_templates:
  - 'khaliq/ncp:{{ .Tag }}-arm64'
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64/v8"
  goarch: arm64

docker_manifests:
- name_template: 'khaliq/ncp:{{ .Tag }}'
  image_templates:
  - 'khaliq/ncp:{{ .Tag }}-amd64'
  - 'khaliq/ncp:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/kha7iq/ncp:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-arm64'
- name_template: 'khaliq/ncp:latest'
  image_templates:
  - 'khaliq/ncp:{{ .Tag }}-amd64'
  - 'khaliq/ncp:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/kha7iq/ncp:latest'
  image_templates:
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-amd64'
  - 'ghcr.io/kha7iq/ncp:{{ .Tag }}-arm64'
