name: Release Chocolatey Package

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  release-chocolatey:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: Release NCP Chocolatey Package
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --config .github/choco/release.yaml
        env:
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
